title: Cookbook Shelf
description: "The cookbooks on my shelf, and my home recipes"

url: http://projects.bmannconsulting.com
baseurl: "/cookbookshelf"
permalink: post/:title/

collections:
  recipes:
    output: true
    permalink: /recipe/:title/
  cookbooks:
    output: true
    permalink: /cookbook/:title/

highlighter: pygments

exclude: ["config.rb"]

navigation:
 - title: Home
   url: /
 - title: Recipe Archive
   url: /archive
 - title: Cookbook Archive
   url: /cookbooks

social:
   github: bmann
   twitter: bmann
   facebook: bmann
   email: boris@bmann.ca

amazonid: cookshel-20
google_analytics: "UA-"
