title: Cookbook Shelf
description: "The cookbooks on my shelf, and my home recipes"

url: http://projects.bmannconsulting.com
baseurl: "/cookbookshelf"
permalink: post/:title/

collections:
  recipes:
    output: true
    permalink: /recipe/:title/

markdown: redcarpet
highlighter: pygments

exclude: ["config.rb"]

navigation:
 - title: Home
   url: /
 - title: Recipe Archive
   url: /archive

social:
   github: bmann
   twitter: bmann
   facebook: bmann
   email: boris@bmann.ca

google_analytics: "UA-"
